### ISSUE TITLE
ESPHome 2026 compile errors (`error: no matching function for call`)

### ISSUE THREAD

**Issue by scy** [s-marian/esphome-components-mma8452q#2]
ESPHome has deprecated some arguments in the I²C API, which means that this component no longer compiles in 2026.3 or higher (and maybe even lower). Symptoms look like this:

```
[5/12] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/mma8452q/mma8452q.cpp.obj
FAILED: esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/mma8452q/mma8452q.cpp.obj 
/home/scy/.cache/esphome/idf/tools/xtensa-esp-elf/esp-14.2.0_20260121/xtensa-esp-elf/bin/xtensa-esp32-elf-g++ @esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/mma8452q/mma8452q.cpp.obj.rsp -MD -MT esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/mma8452q/mma8452q.cpp.obj -MF esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/mma8452q/mma8452q.cpp.obj.d -o esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/mma8452q/mma8452q.cpp.obj -c /home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp
/home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp: In member function 'void esphome::mma8452q::MMA8452QComponent::writeRegisters(esphome::mma8452q::MMA8452Q_Register, byte*, byte)':
/home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp:43:16: error: no matching function for call to 'esphome::mma8452q::MMA8452QComponent::write(uint8_t*, unsigned int, int)'
   43 |     this->write((uint8_t*)&reg, sizeof(reg), 0);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.h:5,
                 from /home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp:1:
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:183:13: note: candidate: 'esphome::i2c::ErrorCode esphome::i2c::I2CDevice::write(const uint8_t*, size_t) const'
  183 |   ErrorCode write(const uint8_t *data, size_t len) const {
      |             ^~~~~
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:183:13: note:   candidate expects 2 arguments, 3 provided
/home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp: In member function 'byte esphome::mma8452q::MMA8452QComponent::readRegister(esphome::mma8452q::MMA8452Q_Register)':
/home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp:64:24: error: no matching function for call to 'esphome::mma8452q::MMA8452QComponent::read_byte(esphome::mma8452q::MMA8452Q_Register&, uint8_t*, bool)'
   64 |     if(!this->read_byte(reg, &byte, false)) {
      |         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:240:8: note: candidate: 'bool esphome::i2c::I2CDevice::read_byte(uint8_t, uint8_t*)'
  240 |   bool read_byte(uint8_t a_register, uint8_t *data) { return read_register(a_register, data, 1) == ERROR_OK; }
      |        ^~~~~~~~~
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:240:8: note:   candidate expects 2 arguments, 3 provided
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:242:21: note: candidate: 'std::optional<unsigned char> esphome::i2c::I2CDevice::read_byte(uint8_t)'
  242 |   optional<uint8_t> read_byte(uint8_t a_register) {
      |                     ^~~~~~~~~
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:242:21: note:   candidate expects 1 argument, 3 provided
/home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp: In member function 'void esphome::mma8452q::MMA8452QComponent::readRegisters(esphome::mma8452q::MMA8452Q_Register, byte*, byte)':
/home/scy/foo/.esphome/build/garnet/src/esphome/components/mma8452q/mma8452q.cpp:106:24: error: no matching function for call to 'esphome::mma8452q::MMA8452QComponent::read_register(esphome::mma8452q::MMA8452Q_Register&, byte*&, byte&, int)'
  106 |     this->read_register(reg, buffer, len, 0);
      |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:170:13: note: candidate: 'esphome::i2c::ErrorCode esphome::i2c::I2CDevice::read_register(uint8_t, uint8_t*, size_t)'
  170 |   ErrorCode read_register(uint8_t a_register, uint8_t *data, size_t len);
      |             ^~~~~~~~~~~~~
/home/scy/foo/.esphome/build/garnet/src/esphome/components/i2c/i2c.h:170:13: note:   candidate expects 3 arguments, 4 provided
[6/12] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/main.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/scy/foo/.esphome/build/garnet/build/log/idf_py_stderr_output_1098358 and /home/scy/foo/.esphome/build/garnet/build/log/idf_py_stdout_output_1098358
```

I've forked the component to https://codeberg.org/scy/esphome-component-mma8452q, fixed the compile errors, implemented some additional minor fixes (like removing the `m/s²` unit from the `accel_*` sensor values because it's incorrect), and added a readme with documentation.

Let me know if you want me to create pull requests for these changes.
